name = "shrink-my-link"
compatibility_date = "2024-04-02"
pages_build_output_dir = ".svelte-kit/cloudflare"


kv_namespaces = [
  { binding = "ns_shrink_my_linkkv_namespaces = [
    { binding = "LINKS", id = "404aff27168b497792de35d9c836f1f7" }
  ]", id = "404aff27168b497792de35d9c836f1f7" }
]